/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminRestaurantsRouteImport } from './routes/super-admin.restaurants'
import { Route as SuperAdminBranchesRouteImport } from './routes/super-admin.branches'
import { Route as SuperAdminBillingRouteImport } from './routes/super-admin.billing'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminRestaurantsRoute = SuperAdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBranchesRoute = SuperAdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBillingRoute = SuperAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SuperAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/branches': typeof SuperAdminBranchesRoute
  '/super-admin/restaurants': typeof SuperAdminRestaurantsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/branches': typeof SuperAdminBranchesRoute
  '/super-admin/restaurants': typeof SuperAdminRestaurantsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/branches': typeof SuperAdminBranchesRoute
  '/super-admin/restaurants': typeof SuperAdminRestaurantsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/super-admin'
    | '/super-admin/billing'
    | '/super-admin/branches'
    | '/super-admin/restaurants'
    | '/super-admin/users'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/super-admin/billing'
    | '/super-admin/branches'
    | '/super-admin/restaurants'
    | '/super-admin/users'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/super-admin'
    | '/super-admin/billing'
    | '/super-admin/branches'
    | '/super-admin/restaurants'
    | '/super-admin/users'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/restaurants': {
      id: '/super-admin/restaurants'
      path: '/restaurants'
      fullPath: '/super-admin/restaurants'
      preLoaderRoute: typeof SuperAdminRestaurantsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/branches': {
      id: '/super-admin/branches'
      path: '/branches'
      fullPath: '/super-admin/branches'
      preLoaderRoute: typeof SuperAdminBranchesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/billing': {
      id: '/super-admin/billing'
      path: '/billing'
      fullPath: '/super-admin/billing'
      preLoaderRoute: typeof SuperAdminBillingRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminBillingRoute: typeof SuperAdminBillingRoute
  SuperAdminBranchesRoute: typeof SuperAdminBranchesRoute
  SuperAdminRestaurantsRoute: typeof SuperAdminRestaurantsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminBillingRoute: SuperAdminBillingRoute,
  SuperAdminBranchesRoute: SuperAdminBranchesRoute,
  SuperAdminRestaurantsRoute: SuperAdminRestaurantsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
